/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAM215
 */
public class menuCategorias extends javax.swing.JFrame {

    /**
     * Creates new form menuCategorias
     */
    public menuCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_categorias = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rb_cie = new javax.swing.JRadioButton();
        rb_dep = new javax.swing.JRadioButton();
        rb_geo = new javax.swing.JRadioButton();
        rb_his = new javax.swing.JRadioButton();
        rb_mus = new javax.swing.JRadioButton();
        rb_ser = new javax.swing.JRadioButton();
        btn_comenzar = new javax.swing.JButton();
        btn_desconectar = new javax.swing.JButton();
        rb_ale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CATEGORÍAS DE LAS PREGUNTAS");

        bg_categorias.add(rb_cie);
        rb_cie.setText("Ciencias");
        rb_cie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cieActionPerformed(evt);
            }
        });

        bg_categorias.add(rb_dep);
        rb_dep.setText("Deportes");

        bg_categorias.add(rb_geo);
        rb_geo.setText("Geografía");

        bg_categorias.add(rb_his);
        rb_his.setText("Historia");

        bg_categorias.add(rb_mus);
        rb_mus.setText("Música");

        bg_categorias.add(rb_ser);
        rb_ser.setText("Series TV");

        btn_comenzar.setText("COMENZAR");
        btn_comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comenzarActionPerformed(evt);
            }
        });

        btn_desconectar.setText("DESCONECTAR");
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });

        bg_categorias.add(rb_ale);
        rb_ale.setText("Aleatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_cie)
                    .addComponent(rb_dep)
                    .addComponent(rb_geo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_mus)
                    .addComponent(rb_his)
                    .addComponent(rb_ser))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btn_comenzar)
                        .addGap(61, 61, 61)
                        .addComponent(btn_desconectar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(rb_ale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cie)
                    .addComponent(rb_his))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_dep)
                    .addComponent(rb_mus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_geo)
                    .addComponent(rb_ser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_ale)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_comenzar)
                    .addComponent(btn_desconectar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_cieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_cieActionPerformed

    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Inicio in=new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_btn_desconectarActionPerformed

    private void btn_comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comenzarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        String categoria="";
        String cod="";
        
        if(rb_cie.isSelected()){
            categoria="Ciencia";
            cod="CIE";
        }else if(rb_dep.isSelected()){
            categoria="Deportes";
            cod="DEP";
        }else if(rb_geo.isSelected()){
            categoria="Geografía";
            cod="GEO";
        }else if(rb_his.isSelected()){
            categoria="Historia";
            cod="HIS";
        }else if(rb_mus.isSelected()){
            categoria="Música";
            cod="MUS";
        }else if(rb_ser.isSelected()){
            categoria="Series de TV";
            cod="SER";
        }else if(rb_ale.isSelected()){
            categoria="Aleatorio";
            cod=null;
        }
        
        cuestionario c=new cuestionario(categoria, cod);
        c.setVisible(true);
    }//GEN-LAST:event_btn_comenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_categorias;
    private javax.swing.JButton btn_comenzar;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rb_ale;
    private javax.swing.JRadioButton rb_cie;
    private javax.swing.JRadioButton rb_dep;
    private javax.swing.JRadioButton rb_geo;
    private javax.swing.JRadioButton rb_his;
    private javax.swing.JRadioButton rb_mus;
    private javax.swing.JRadioButton rb_ser;
    // End of variables declaration//GEN-END:variables
}
